# dockerfile used to build the base image used in ./Dockerfile
FROM reg.aichallenge.ir/python:3.8

RUN apt update && apt install -y vim curl gettext
RUN apt-get update && \
apt install -y vim curl gettext cmake unzip && \
pip3 install pyinstaller pandas scipy scikit-learn numpy

